name: gymgym-web CI
env:
  cache-version: v1
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache docker images
        uses: actions/cache@v2
        id: cache-docker
        env:
          cache-name: docker-image
        with:
          path: ~/docker_images
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('api/Dockerfile', 'Gemfile.lock') }}
      - name: build docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: make build
      - name: save docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: mkdir -p ~/docker_images && docker save gymgym-web_api:latest > ~/docker_images/gymgym-web_api_latest.tar
  rubocop_rspec:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache docker images
        uses: actions/cache@v2
        id: cache-docker
        env:
          cache-name: docker-image
        with:
          path: ~/docker_images
          key: ${{ env.cache-version }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('api/Dockerfile', 'Gemfile.lock') }}
      - name: load docker image
        run: docker load < ~/docker_images/gymgym-web_api_latest.tar
      - name: run rubocop
        id: rubocop
        run: make rubocop
